include: package:lints/recommended.yaml

analyzer:
  exclude:
    - .worktrees/**
    - third/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
