name: cockpit_workspace

packages:
  - packages/cockpit_protocol
  - packages/flutter_cockpit
  - packages/flutter_cockpit_test
  - packages/cockpit
  - packages/cockpit_console
  - examples/cockpit_demo
  - examples/cockpit_demo/cockpit

scripts:
  analyze:
    run: dart analyze
  test:
    run: >-
      (dart test test) &&
      (flutter test --no-pub packages/flutter_cockpit/test) &&
      (flutter test --no-pub packages/flutter_cockpit_test/test) &&
      (cd packages/cockpit && dart test test) &&
      (cd examples/cockpit_demo && flutter test --no-pub) &&
      (cd examples/cockpit_demo/cockpit && flutter test --no-pub)
