import '../foundation/cockpit_enum.dart';

enum CockpitCommandType {
  tap,
  hover,
  wheel,
  enterText,
  eraseText,
  copyText,
  pasteText,
  focusTextInput,
  setTextEditingValue,
  sendTextInputAction,
  sendKeyEvent,
  sendKeyDownEvent,
  sendKeyUpEvent,
  longPress,
  doubleTap,
  drag,
  fling,
  swipe,
  pinchZoom,
  rotate,
  panZoom,
  multiTouch,
  scrollUntilVisible,
  clearNetworkActivity,
  waitForNetworkIdle,
  waitForUiIdle,
  back,
  showOnScreen,
  increase,
  decrease,
  dismiss,
  dismissKeyboard,
  waitFor,
  assertVisible,
  assertText,
  assertScreenshot,
  travel,
  system,
  captureScreenshot,
  collectSnapshot,
  describeApp,
  appAction;

  static CockpitCommandType fromJson(
    Object? json, {
    String path = r'$.commandType',
  }) => cockpitEnumFromJson(json, values, path);
}
