/// Synthetic pattern-app generator: emits small, cockpit-drivable Flutter
/// apps that exercise one UI pattern each, with seeded variation so a
/// dataset can cover many distinct apps cheaply.
///
/// Patterns:
/// - `settings_flow` — grouped toggles/preferences with a save action.
/// - `form_flow`     — multi-field form with a submit → confirmation flow.
/// - `lazy_feed`     — long lazy list with detail navigation.
library;

import 'dart:math';

enum PatternAppKind { settingsFlow, formFlow, lazyFeed }

String patternAppKindToString(PatternAppKind kind) {
  return switch (kind) {
    PatternAppKind.settingsFlow => 'settings_flow',
    PatternAppKind.formFlow => 'form_flow',
    PatternAppKind.lazyFeed => 'lazy_feed',
  };
}

PatternAppKind patternAppKindFromString(String value) {
  return PatternAppKind.values.firstWhere(
    (kind) => patternAppKindToString(kind) == value,
    orElse: () => throw FormatException('Unknown pattern app kind: $value'),
  );
}

/// Generated output: the app name and its file contents, keyed by path
/// relative to the app directory.
class PatternAppOutput {
  const PatternAppOutput({required this.name, required this.files});

  final String name;
  final Map<String, String> files;
}

class PatternAppGenerator {
  const PatternAppGenerator();

  PatternAppOutput generate({
    required PatternAppKind kind,
    required String name,
    required int seed,
    required String flutterCockpitPath,
  }) {
    final random = Random(seed);
    return PatternAppOutput(
      name: name,
      files: <String, String>{
        'pubspec.yaml': _pubspec(
          name: name,
          kind: kind,
          seed: seed,
          flutterCockpitPath: flutterCockpitPath,
        ),
        'main.dart': _mainDart(
          kind: kind,
          random: random,
          appTitle: _appTitle(name),
          className: _pascalCase(name),
        ),
        'README.md': _readme(name: name, kind: kind, seed: seed),
      },
    );
  }

  String _pubspec({
    required String name,
    required PatternAppKind kind,
    required int seed,
    required String flutterCockpitPath,
  }) {
    return '''
name: $name
description: Generated Cockpit pattern app
  (${patternAppKindToString(kind)}, seed $seed) for agent trajectory recording.
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_cockpit:
    path: $flutterCockpitPath
flutter:
  uses-material-design: true
''';
  }

  String _readme({
    required String name,
    required PatternAppKind kind,
    required int seed,
  }) {
    return '''
# $name

Generated Cockpit pattern app: `${patternAppKindToString(kind)}` (seed $seed).
Regenerate with `dart run tool/gen_pattern_app.dart` instead of editing.

```bash
flutter pub get
cockpit dev start --platform macos
```
''';
  }

  String _mainDart({
    required PatternAppKind kind,
    required Random random,
    required String appTitle,
    required String className,
  }) {
    final home = switch (kind) {
      PatternAppKind.settingsFlow => _settingsSource(random),
      PatternAppKind.formFlow => _formSource(random),
      PatternAppKind.lazyFeed => _feedSource(random),
    };
    return '''
// Generated by tool/gen_pattern_app.dart — do not edit.
import 'package:flutter/material.dart';
import 'package:flutter_cockpit/flutter_cockpit_flutter.dart';

void main() => runApp(const ${className}App());

class ${className}App extends StatelessWidget {
  const ${className}App({super.key});

  @override
  Widget build(BuildContext context) {
    return FlutterCockpitApp(
      config: FlutterCockpitConfig.fromRuntimeConfiguration(
        FlutterCockpitConfiguration(
          remoteSession:
              CockpitRemoteSessionConfiguration.resolveFromEnvironment(
                fallback: const CockpitRemoteSessionConfiguration(
                  enabled: true,
                  host: '127.0.0.1',
                  port: 47331,
                ),
              ),
        ),
      ),
      child: MaterialApp(
        title: ${_dartString(appTitle)},
        home: const ${home.homeScreenName}(),
      ),
    );
  }
}

${home.source}
''';
  }
}

/// Widget-source bundle for one pattern: the home screen class name plus
/// the Dart source of all screens below the app shell.
class _PatternSource {
  const _PatternSource(this.homeScreenName, this.source);

  final String homeScreenName;
  final String source;
}

_PatternSource _settingsSource(Random random) {
  final sections = <String>[..._settingSections.keys]..shuffle(random);
  final selected = sections.take(3 + random.nextInt(2));
  final sectionCode = selected.map((section) {
    final items = <String>[..._settingSections[section]!]..shuffle(random);
    final picked = items.take(2 + random.nextInt(2));
    final itemCode = picked
        .map((item) {
          final initial = random.nextBool();
          return '        _SettingItem(label: ${_dartString(item)}, initialValue: $initial),';
        })
        .join('\n');
    return '''
      _Section(
        header: ${_dartString(section)},
        items: [
$itemCode
        ],
      ),
''';
  }).join();
  return _PatternSource('SettingsScreen', '''
class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  final Map<String, bool> _states = {};

  List<_Section> get _sections => [
$sectionCode  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Preferences')),
      body: ListView(
        children: [
          for (final section in _sections)
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(16, 24, 16, 8),
                  child: Text(
                    section.header,
                    style: Theme.of(context).textTheme.titleLarge,
                  ),
                ),
                for (final item in section.items)
                  SwitchListTile(
                    title: Text(item.label),
                    value: _states[item.label] ?? item.initialValue,
                    onChanged: (value) =>
                        setState(() => _states[item.label] = value),
                  ),
              ],
            ),
        ],
      ),
      bottomNavigationBar: Padding(
        padding: const EdgeInsets.all(16),
        child: FilledButton(
          onPressed: () => ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Preferences saved')),
          ),
          child: const Text('Save preferences'),
        ),
      ),
    );
  }
}

class _Section {
  const _Section({required this.header, required this.items});

  final String header;
  final List<_SettingItem> items;
}

class _SettingItem {
  const _SettingItem({required this.label, required this.initialValue});

  final String label;
  final bool initialValue;
}
''');
}

_PatternSource _formSource(Random random) {
  final fields = <String>[..._formFields]..shuffle(random);
  final picked = fields.take(3 + random.nextInt(2));
  final fieldCode = picked
      .map((field) => '        ${_dartString(field)},')
      .join('\n');
  return _PatternSource('SubmitFormScreen', '''
class SubmitFormScreen extends StatefulWidget {
  const SubmitFormScreen({super.key});

  @override
  State<SubmitFormScreen> createState() => _SubmitFormScreenState();
}

class _SubmitFormScreenState extends State<SubmitFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final Map<String, TextEditingController> _controllers = {
    for (final field in const <String>[
$fieldCode
    ])
      field: TextEditingController(),
  };

  @override
  void dispose() {
    for (final controller in _controllers.values) {
      controller.dispose();
    }
    super.dispose();
  }

  void _submit() {
    if (_formKey.currentState?.validate() != true) return;
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => ConfirmationScreen(
          entries: {
            for (final field in _controllers.keys)
              field: _controllers[field]!.text,
          },
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Submit request')),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            for (final field in _controllers.keys)
              Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: TextFormField(
                  controller: _controllers[field],
                  decoration: InputDecoration(labelText: field),
                  validator: (value) =>
                      (value == null || value.isEmpty)
                          ? '\$field is required'
                          : null,
                ),
              ),
            FilledButton(
              onPressed: _submit,
              child: const Text('Submit request'),
            ),
          ],
        ),
      ),
    );
  }
}

class ConfirmationScreen extends StatelessWidget {
  const ConfirmationScreen({super.key, required this.entries});

  final Map<String, String> entries;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Request submitted')),
      body: ListView(
        children: [
          for (final entry in entries.entries)
            ListTile(title: Text(entry.key), subtitle: Text(entry.value)),
        ],
      ),
    );
  }
}
''');
}

_PatternSource _feedSource(Random random) {
  final topics = <String>[..._feedTopics]..shuffle(random);
  final picked = topics.take(3).toList();
  final itemCount = 24 + random.nextInt(24);
  final items = List.generate(
    itemCount,
    (index) => '${picked[index % picked.length]} ${index + 1}',
  );
  final itemCode = items.map((item) => '    ${_dartString(item)},').join('\n');
  return _PatternSource('FeedScreen', '''
class FeedScreen extends StatelessWidget {
  const FeedScreen({super.key});

  static const List<String> _items = [
$itemCode
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Browse')),
      body: ListView.builder(
        itemCount: _items.length,
        itemBuilder: (context, index) {
          final title = _items[index];
          return ListTile(
            title: Text(title),
            subtitle: Text('Item \$index of \${_items.length}'),
            onTap: () => Navigator.of(context).push(
              MaterialPageRoute<void>(
                builder: (_) => DetailScreen(title: title, index: index),
              ),
            ),
          );
        },
      ),
    );
  }
}

class DetailScreen extends StatelessWidget {
  const DetailScreen({super.key, required this.title, required this.index});

  final String title;
  final int index;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text('Entry \$index', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 8),
          const Text(
            'This detail page exists so feed navigation has a destination '
            'worth inspecting and a back path worth exercising.',
          ),
        ],
      ),
    );
  }
}
''');
}

const Map<String, List<String>> _settingSections = <String, List<String>>{
  'General': <String>[
    'Start on dashboard',
    'Confirm before closing',
    'Show onboarding tips',
  ],
  'Appearance': <String>[
    'Reduce motion',
    'High contrast tiles',
    'Show avatars',
  ],
  'Notifications': <String>[
    'Mention alerts',
    'Daily digest',
    'Delivery updates',
    'Quiet hours',
  ],
  'Privacy': <String>['Share usage stats', 'Personalized suggestions'],
  'Sync': <String>['Sync on Wi-Fi only', 'Background refresh'],
};

const List<String> _formFields = <String>[
  'Full name',
  'Contact email',
  'Organization',
  'Department',
  'City',
  'Referral code',
  'Notes',
];

const List<String> _feedTopics = <String>[
  'Field notes',
  'Release digest',
  'Trail report',
  'Workshop recap',
  'Studio update',
  'Dispatch',
];

String _dartString(String value) => "'${value.replaceAll("'", r"\'")}'";

String _pascalCase(String name) {
  return name
      .split(RegExp(r'[^a-zA-Z0-9]+'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1).toLowerCase())
      .join();
}

String _appTitle(String name) {
  final pascal = _pascalCase(name);
  return pascal.isEmpty ? 'Pattern app' : '$pascal app';
}
