part of 'cockpit_supervisor_operation_schema.dart';

final Map<String, Object?> _runAcceptedResponse = _object(
  properties: const <String, Object?>{
    'workspaceId': _id,
    'runId': _id,
    'statusUrl': _string,
    'eventsUrl': _string,
    'submittedAt': _utcTimestamp,
    'replayed': _boolean,
  },
  required: const <String>[
    'workspaceId',
    'runId',
    'statusUrl',
    'eventsUrl',
    'submittedAt',
    'replayed',
  ],
);

final Map<String, Map<String, Object?>> _responseSchemas =
    <String, Map<String, Object?>>{
      'target.discover': _object(
        properties: <String, Object?>{'targets': _array(_jsonObject)},
        required: const <String>['targets'],
        precision: 'structural',
      ),
      'lease.list': _object(
        properties: <String, Object?>{'items': _array(_jsonObject)},
        required: const <String>['items'],
        precision: 'structural',
      ),
      'lease.recover': _object(
        properties: const <String, Object?>{
          'leaseId': _id,
          'workspaceId': _id,
          'resourceKind': _string,
          'resourceId': _string,
          'holderId': _id,
          'beforeState': _string,
          'afterState': _string,
          'cleanupVerified': _boolean,
          'forceReleased': _boolean,
          'lease': _jsonObject,
        },
        required: const <String>[
          'leaseId',
          'workspaceId',
          'resourceKind',
          'resourceId',
          'holderId',
          'beforeState',
          'afterState',
          'cleanupVerified',
          'forceReleased',
          'lease',
        ],
        precision: 'structural',
      ),
      'system.capabilities': _structuralResponse(
        'System-control capabilities and current availability.',
      ),
      'system.diagnostics': _object(
        properties: const <String, Object?>{
          'engineVersion': _string,
          'draining': _boolean,
          'rootCount': _integer,
          'activeRootCount': _integer,
          'workspaceCount': _integer,
          'activeWorkspaceCount': _integer,
          'activeWorkerCount': _integer,
          'projectionCount': _integer,
          'permissionPolicy': _string,
        },
        required: const <String>[
          'engineVersion',
          'draining',
          'rootCount',
          'activeRootCount',
          'workspaceCount',
          'activeWorkspaceCount',
          'activeWorkerCount',
          'projectionCount',
          'permissionPolicy',
        ],
      ),
      'project.create': _object(
        properties: const <String, Object?>{
          'projectDirectory': _string,
          'command': _jsonObject,
          'success': _boolean,
          'stdout': <String, Object?>{'type': 'string'},
          'stderr': <String, Object?>{'type': 'string'},
        },
        required: const <String>[
          'projectDirectory',
          'command',
          'success',
          'stdout',
          'stderr',
        ],
        precision: 'structural',
      ),
      'package.search': _object(
        properties: <String, Object?>{
          'results': _array(_jsonObject),
          'warnings': _stringList,
          'suggestion': <String, Object?>{
            'type': <String>['string', 'null'],
          },
        },
        required: const <String>['results', 'warnings', 'suggestion'],
        precision: 'structural',
      ),
      'document.index': _object(
        properties: const <String, Object?>{
          'documentCount': _integer,
          'matchedCount': _integer,
        },
        required: const <String>['documentCount'],
      ),
      'document.list': _object(
        properties: <String, Object?>{
          'documents': _array(_jsonObject),
          'totalCount': _integer,
        },
        required: const <String>['documents', 'totalCount'],
        precision: 'structural',
      ),
      'case.validate': _object(
        properties: <String, Object?>{
          'valid': _boolean,
          'sourceSha256': _sha256,
          'document': _jsonObject,
          'diagnostics': _array(_jsonObject),
          'sourceMap': _array(_jsonObject),
        },
        required: const <String>[
          'valid',
          'sourceSha256',
          'diagnostics',
          'sourceMap',
        ],
        precision: 'structural',
      ),
      'case.run': _runAcceptedResponse,
      'suite.run': _runAcceptedResponse,
      for (final kind in <String>[
        'analyze.files',
        'analyze.workspace',
        'fix.workspace',
        'format.workspace',
        'test.workspace',
        'package.pub',
        'lsp.request',
      ])
        kind: _structuralResponse('$kind result.'),
      'package.uris.read': _object(
        properties: <String, Object?>{
          'uri': _string,
          'kind': _string,
          'contentKind': _string,
          'preview': <String, Object?>{'type': 'string'},
          'text': <String, Object?>{'type': 'string'},
          'mediaType': <String, Object?>{'type': 'string'},
          'totalBytes': _integer,
          'entryCount': _integer,
          'truncated': _boolean,
          'entries': _array(_jsonObject),
        },
        required: const <String>[
          'uri',
          'kind',
          'contentKind',
          'entryCount',
          'truncated',
          'entries',
        ],
        precision: 'structural',
      ),
      'package.uris.grep': _structuralResponse(
        'Bounded package URI search result.',
        properties: <String, Object?>{
          'query': _string,
          'packages': _array(_jsonObject),
          'truncated': _boolean,
          'summary': _string,
        },
        required: const <String>['query', 'packages', 'truncated', 'summary'],
      ),
      'app.list': _object(
        properties: <String, Object?>{'apps': _array(_jsonObject)},
        required: const <String>['apps'],
        precision: 'structural',
      ),
      'target.list': _object(
        properties: <String, Object?>{'targets': _array(_jsonObject)},
        required: const <String>['targets'],
        precision: 'structural',
      ),
      'target.get': _object(
        properties: const <String, Object?>{'target': _jsonObject},
        required: const <String>['target'],
        precision: 'structural',
      ),
      'target.register': _object(
        properties: const <String, Object?>{'targetId': _id},
        required: const <String>['targetId'],
      ),
      for (final kind in <String>[
        'app.get',
        'target.inspect',
        'app.launch',
        'target.launch',
        'app.stop',
        'session.remote.launch',
        'session.remote.get',
        'session.remote.status',
        'snapshot.remote.read',
        'snapshot.remote.collect',
        'command.remote.execute',
        'command.remote.batch',
        'ui.remote.waitIdle',
        'session.development.launch',
        'session.development.get',
        'session.development.reload',
        'session.development.stop',
        'development.probe.collect',
        'development.probe.compare',
        'ui.inspect',
        'surface.inspect',
        'logs.read',
        'network.read',
        'network.body',
        'errors.read',
        'session.logs.read',
        'evidence.screenshot.capture',
        'command.run',
        'command.batch',
        'shell.run',
        'system.action',
        'app.reload',
        'app.restart',
        'ui.waitIdle',
        'viewport.set',
        'recording.start',
        'recording.stop',
      ])
        kind: _structuralResponse('$kind result.'),
    };
